Turaco = require "turaco.methods"
-- TODO: editable bespoke colorscheme
-- behavior: floating window with all colorscheme fields/options in vim to edit
-- can switch to the bespoke colorscheme like the default colorscheme

Turaco.Stack = Turaco.Load()
-- Turaco.StrStack = Turaco.Str(Turaco.Stack)

-- TODO: implement live_preview for the paints stack window
-- local win_id
--
-- function ShowMenu(opts, cb)
-- 	local height = 30
-- 	local width = 70
-- 	local borderchars = { '-', '|', '-', '|', '╭', '╮', '╯', '╰' }
--
-- 	WinId = popup.create(opts, {
-- 		title = "test window",
-- 		highlight = "twin",
-- 		line = math.floor(((vim.o.lines - height) / 2) - 1),
-- 		col = math.floor((vim.o.columns - width) /2),
-- 		minwidth = width,
-- 		minheight = height,
-- 		borderchars= borderchars,
-- 		callback = cb,
-- 	})
-- 	local bufnr = vim.api.nvim_win_get_buf(WinId)
-- 	vim.api.nvim_buf_set_keymap(bufnr, 'n', '=', '<cmd>lua CloseMenu()<cr>', { silent = false })
-- end
--
-- function CloseMenu()
-- 	vim.api.nvim_win_close(WinId, true)
-- end
--
-- function DeployMenu()
-- 	local opts = Turaco.Stack
-- 	
-- 	local cb = function(_, sel)
-- 		Turaco.Paint(sel)
-- 	end
-- 	ShowMenu(opts, cb)
-- end
